# Generated by Django 4.1.5 on 2023-01-25 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("image_url", models.URLField()),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Personaje",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("image_url", models.URLField()),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("edad", models.PositiveSmallIntegerField()),
                ("nacionalidad", models.CharField(max_length=15)),
                ("raza", models.CharField(max_length=10)),
                (
                    "universo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.universo",
                    ),
                ),
            ],
        ),
    ]
