# Generated by Django 4.1.5 on 2023-01-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="personaje", name="image",),
        migrations.RemoveField(model_name="universo", name="image",),
    ]
