# Generated by Django 4.1.5 on 2023-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0003_personaje_descripcion_alter_personaje_universo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaje",
            name="image_url",
            field=models.CharField(max_length=99999),
        ),
        migrations.AlterField(
            model_name="universo",
            name="image_url",
            field=models.CharField(max_length=99999),
        ),
    ]
